### PR TITLE
Upgrading to node 6.11.1

### PR DESCRIPTION
**Pull request by bleveque**
[ticket](https://trello.com/c/Bbjbowex/370-upgrade-hookshot-to-node-6111)

Tested app.js and release.js out on a test github repo and test trello board.

@judyhe @hwigmore

### CODE REVIEW

**Comment by hwigmore** [comment]
👍

**Comment by hwigmore** [comment]
oh i had a thought this morning. should we change protofit and depot to plans and build in the release print out?

**Comment by judyhe** [comment]
👍

**Comment by bleveque** [comment]
oh yeah, good call! updated and pushed (without testing)

**Comment by hwigmore** [comment]
great thanks! 👍

**Pull request merged**
